### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by winwisely99** [carzacc/jwt-tutorial-flutter#2]
Web secure storage plugin does not exist.

What do you recommend.
Shared preference or hive maybe ?

**Comment by carzacc** [comment]
Working on a tutorial about that. Probably will release some time this weekend or at the start of next week. Short answer: httpOnly cookies from backend+CSRF protection in localStorage with dart:html or shared_preferences.
________________________________
Da: winwisely99 <notifications@github.com>
Inviato: venerdì 24 aprile 2020 11:39
A: carzacc/jwt-tutorial-flutter <jwt-tutorial-flutter@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [carzacc/jwt-tutorial-flutter] Flutter Web (#2)


Web secure storage plugin does not exist.

What do you recommend.
Shared preference or hive maybe ?

**Comment by carzacc** [comment]
@winwisely99 the code for both the backend and the app is on my GitHub, in case you are impatient, a blog post detailing everything is coming tomorrow if everything goes according to plan.

**Comment by carzacc** [comment]
@winwisely99 There you go https://carmine.dev/posts/flutterwebjwt/
